### ISSUE TITLE
Make updating Travis configurations easier

### ISSUE THREAD

**Issue by desrosj** [wp-cli/wp-cli-dev#4]
Currently, there is no easy way to update Travis (and Composer?) configurations across multiple repositories.

For example, [wp-cli/wp-cli#5073]((https://github.com/wp-cli/wp-cli/pull/5073) changes the default PHP version to 7.3 and introduces a test job for 7.3, but this change only takes effect on that repo. This is a change that should be reflected across all command repositories.

Ideally, there would be a way to deploy all or part of the Travis configuration automatically to the command repositories. I spot checked a handful of `-command` repos and the configuration files are mostly the same, ignoring a few instances where changes were not made to certain repos (using `precise` on 5.4, for example).

There are likely to be ways parts of the `composer.json` file could also be automated.

This was briefly discussed today in the [#cli Slack](https://wordpress.slack.com/archives/C02RP4T41/p1550007714089800) and https://github.com/mixu/gr was brought up.

**Comment by schlessera** [comment]
There's now a GitHub Actions workflow that takes care of this. A centralized file like `.travis.yml` will go into the `wp-cli/.github` repository, and the GHA workflow contains a list of repositories that changes will automatically be replicated to.

See https://github.com/wp-cli/.github/blob/master/.github/workflows/sync-workflows.yml
