### ISSUE TITLE
`wp-cli/.github/` repository not cloned

### ISSUE THREAD

**Issue by swissspidy** [wp-cli/wp-cli-dev#48]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [ ] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

The https://github.com/wp-cli/.github/ repository is not being cloned / available when using wp-cli-dev. I guess it's because there's already a folder with the same name. Maybe we can clone it to `.github-repo` or something?

**Comment by danielbachhuber** [comment]
I clone mine to wp-cli-github in a separate repository...
