### ISSUE TITLE
Use Git repository checkout instead of HTTPS

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli-dev#5]
Can we switch from `https://github.com/wp-cli/scaffold-command.git` to `git@github.com:wp-cli/scaffold-command.git` ?

With the former, I get a password prompt when trying to push:

<img width="638" alt="image" src="https://user-images.githubusercontent.com/36432/52720059-c4b16400-2f5b-11e9-9635-1f27c6456bc1.png">

**Comment by danielbachhuber** [comment]
@schlessera Are you amenable to this change?

**Comment by schlessera** [comment]
@danielbachhuber Yes, I don't think that changes much else, does it?

**Comment by danielbachhuber** [comment]
Nope, pretty much the same.
